### ISSUE TITLE
mysql un/pwd

### ISSUE THREAD

**Issue by drnikko** [thom8/drupal8-vagrant#1]
Hi there,

Everything works perfectly and I'd love to share this with my team without modifications.  Can you tell me the mysql creds?  I tried all the usual suspects and none seemed to work.  

thanks!

**Comment by thom8** [comment]
Hi,

The default root pwd for mysql is root so >>

```
username root 
password root
```

All default config is in the config.yml file -- https://raw.githubusercontent.com/thom8/drupal8-vagrant/master/config.yml *see -- mysql_root_password: root

Still working on some proper docs but more info can be found on the parent project -- https://github.com/thom8/acquia-vagrant
