### ISSUE TITLE
Error during "Install Drupal with drush"

### ISSUE THREAD

**Issue by drupality** [thom8/drupal8-vagrant#10]
Console output:

`fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["/usr/local/bin/drush", "site-install", "standard", "-y", "--site-name=Drupal 8 Sprint Box", "--account-name=admin", "--account-pass=admin", "--db-url=mysql://beetbox:beetbox@localhost/beetbox"], "delta": "0:00:00.308439", "end": "2017-08-01 11:43:26.944201", "failed": true, "rc": 255, "start": "2017-08-01 11:43:26.635762", "stderr": "PHP Fatal error:  Declaration of Drush\\Command\\DrushInputAdapter::hasParameterOption() must be compatible with Symfony\\Component\\Console\\Input\\InputInterface::hasParameterOption($values, $onlyParams = false) in /usr/local/share/drush/lib/Drush/Command/DrushInputAdapter.php on line 27\nPHP Stack trace:\nPHP   1. {main}() /usr/local/share/drush/drush.php:0\nPHP   2. drush_main() /usr/local/share/drush/drush.php:12\nPHP   3. Drush\\Boot\\BaseBoot->bootstrap_and_dispatch() /usr/local/share/drush/includes/preflight.inc:66\nPHP   4. drush_dispatch() /usr/local/share/drush/lib/Drush/Boot/BaseBoot.php:67\nPHP   5. call_user_func_array:{/usr/local/share/drush/includes/command.inc:199}() /usr/local/share/drush/includes/command.inc:199\nPHP   6. drush_command() /usr/local/share/drush/includes/command.inc:199\nPHP   7. _drush_invoke_hooks() /usr/local/share/drush/includes/command.inc:231\nPHP   8. spl_autoload_call() /usr/local/share/drush/includes/command.inc:353\nPHP   9. Composer\\Autoload\\ClassLoader->loadClass() /usr/local/share/drush/includes/command.inc:353\nPHP  10. Composer\\Autoload\\includeFile() /usr/local/share/drush/vendor/composer/ClassLoader.php:322\nPHP  11. include() /usr/local/share/drush/vendor/composer/ClassLoader.php:444\nDrush command terminated abnormally due to an unrecoverable error.       [error]\nError: Declaration of\nDrush\\Command\\DrushInputAdapter::hasParameterOption() must be\ncompatible with\nSymfony\\Component\\Console\\Input\\InputInterface::hasParameterOption($values,\n$onlyParams = false) in\n/usr/local/share/drush/lib/Drush/Command/DrushInputAdapter.php, line\n27", "stdout": "\nFatal error: Declaration of Drush\\Command\\DrushInputAdapter::hasParameterOption() must be compatible with Symfony\\Component\\Console\\Input\\InputInterface::hasParameterOption($values, $onlyParams = false) in /usr/local/share/drush/lib/Drush/Command/DrushInputAdapter.php on line 27\n\nCall Stack:\n    0.0001     223424   1. {main}() /usr/local/share/drush/drush.php:0\n    0.0008     397872   2. drush_main() /usr/local/share/drush/drush.php:12\n    0.1602   11023816   3. Drush\\Boot\\BaseBoot->bootstrap_and_dispatch() /usr/local/share/drush/includes/preflight.inc:66\n    0.1831   10308656   4. drush_dispatch() /usr/local/share/drush/lib/Drush/Boot/BaseBoot.php:67\n    0.2484   12971192   5. call_user_func_array:{/usr/local/share/drush/includes/command.inc:199}() /usr/local/share/drush/includes/command.inc:199\n    0.2484   12971712   6. drush_command() /usr/local/share/drush/includes/command.inc:199\n    0.2486   12977184   7. _drush_invoke_hooks() /usr/local/share/drush/includes/command.inc:231\n    0.2487   12982104   8. spl_autoload_call() /usr/local/share/drush/includes/command.inc:353\n    0.2488   12982536   9. Composer\\Autoload\\ClassLoader->loadClass() /usr/local/share/drush/includes/command.inc:353\n    0.2488   12982688  10. Composer\\Autoload\\includeFile() /usr/local/share/drush/vendor/composer/ClassLoader.php:322\n    0.2490   13008592  11. include('/usr/local/share/drush/lib/Drush/Command/DrushInputAdapter.php') /usr/local/share/drush/vendor/composer/ClassLoader.php:444", "stdout_lines": ["", "Fatal error: Declaration of Drush\\Command\\DrushInputAdapter::hasParameterOption() must be compatible with Symfony\\Component\\Console\\Input\\InputInterface::hasParameterOption($values, $onlyParams = false) in /usr/local/share/drush/lib/Drush/Command/DrushInputAdapter.php on line 27", "", "Call Stack:", "    0.0001     223424   1. {main}() /usr/local/share/drush/drush.php:0", "    0.0008     397872   2. drush_main() /usr/local/share/drush/drush.php:12", "    0.1602   11023816   3. Drush\\Boot\\BaseBoot->bootstrap_and_dispatch() /usr/local/share/drush/includes/preflight.inc:66", "    0.1831   10308656   4. drush_dispatch() /usr/local/share/drush/lib/Drush/Boot/BaseBoot.php:67", "    0.2484   12971192   5. call_user_func_array:{/usr/local/share/drush/includes/command.inc:199}() /usr/local/share/drush/includes/command.inc:199", "    0.2484   12971712   6. drush_command() /usr/local/share/drush/includes/command.inc:199", "    0.2486   12977184   7. _drush_invoke_hooks() /usr/local/share/drush/includes/command.inc:231", "    0.2487   12982104   8. spl_autoload_call() /usr/local/share/drush/includes/command.inc:353", "    0.2488   12982536   9. Composer\\Autoload\\ClassLoader->loadClass() /usr/local/share/drush/includes/command.inc:353", "    0.2488   12982688  10. Composer\\Autoload\\includeFile() /usr/local/share/drush/vendor/composer/ClassLoader.php:322", "    0.2490   13008592  11. include('/usr/local/share/drush/lib/Drush/Command/DrushInputAdapter.php') /usr/local/share/drush/vendor/composer/ClassLoader.php:444"], "warnings": []}`

Drupal version: 8.4.0-dev

**Comment by thom8** [comment]
@drupality can you please try `vagrant destroy && vagrant up` again, I think this might have been an upstream issue with drush.
