### ISSUE TITLE
New DrupalConsole installer instructions. 

### ISSUE THREAD

**Issue by jmolivas** [thom8/drupal8-vagrant#8]
@thom8: Since latest changes on the site and the project the instructions for setting up Drupal Console, have changed I just copied instructions on the home page at http://www.drupalconsole.com :

```
# Run this in your terminal to get the latest Console version:
curl http://drupalconsole.com/installer -L -o drupal.phar

# Or if you don't have curl:
php -r "readfile('http://drupalconsole.com/installer');" > drupal.phar

# Accessing from anywhere on your system:
mv drupal.phar /usr/local/bin/drupal

# Copy configuration files to user home directory:
drupal init [--override]
```

**Comment by thom8** [comment]
This will need to be update upstream -- PR created - https://github.com/geerlingguy/ansible-role-drupal-console/pull/5

**Comment by thom8** [comment]
PR created -- https://github.com/geerlingguy/ansible-role-drupal-console/pull/5

@jmolivas this project will still work however new builds of the base box will fail until this is resolved.

**Comment by thom8** [comment]
PR has been merged.

**Comment by jmolivas** [comment]
@thom8: We enabled SSL on the site. new installer instructions using `https`:

```
# Run this in your terminal to get the latest project version:
curl https://drupalconsole.com/installer -L -o drupal.phar
```
